# we use ROS indigo for now

# Ubuntu 14.04
ubuntu-trusty:
  image: ubuntu:trusty
  variables:
    CI_ROS_DISTRO: indigo
    UBUNTU_DISTRO: trusty

  before_script:
    - sudo apt-get update -qq > /dev/null
    - sudo apt-get install -qq -y wget > /dev/null
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO > /dev/null
    
  stage: build
  script:
    - mkdir v4r-build
    - cd v4r-build
    - cmake ..
    - make -j8

# Ubuntu 14.04 debian package generation
ubuntu-trusty-build-package:
  image: ubuntu:trusty
  variables:
    CI_ROS_DISTRO: indigo
    UBUNTU_DISTRO: trusty

  before_script:
    - sudo apt-get update -qq > /dev/null
    - sudo apt-get install -qq -y wget sed > /dev/null
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO > /dev/null
    - sudo apt-get install -qq -y python-bloom devscripts > /dev/null

  stage: build
  script:
    - bloom-generate debian --os-name ubuntu --os-version $UBUNTU_DISTRO --ros-distro $CI_ROS_DISTRO
    - sed -i 's/dh  $@/dh  $@ --parallel/' debian/rules
    - sed -i 's?v4r\//usr\/lib\/?v4r/usr/lib/:$(CURDIR)/debian/v4r/usr/share/V4R/3rdparty/lib/?' debian/rules
    - debuild -rfakeroot -us -uc -b -j8
    - mkdir build
    - mv ../*.deb build

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*

# Ubuntu 16.04
ubuntu-xenial:
  image: ubuntu:xenial
  variables:
    CI_ROS_DISTRO: kinetic
    UBUNTU_DISTRO: xenial

  before_script:
    - apt-get update -qq > /dev/null
    - apt-get install -qq -y wget sudo > /dev/null
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO

  stage: build
  script:
    - apt-get install -y libgoogle-glog-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev> /dev/null
    - mkdir v4r-build
    - cd v4r-build
    - cmake .. -DPCL_APPS_LIBRARY:=/usr/lib/x86_64-linux-gnu/libpcl_apps.so.1.7
    - make -j8
 
# Ubuntu 16.04 debian package generation 
ubuntu-xenial-build-package: 
  image: ubuntu:xenial 
  variables: 
    CI_ROS_DISTRO: kinetic 
    UBUNTU_DISTRO: xenial 
 
  before_script: 
    - apt-get update -qq > /dev/null
    - apt-get install -qq -y wget sed sudo > /dev/null
    - sudo ./setup.sh $UBUNTU_DISTRO $CI_ROS_DISTRO 
    - sudo apt-get install -qq -y python-bloom devscripts > /dev/null
 
  stage: build 
  script: 
    - bloom-generate debian --os-name ubuntu --os-version $UBUNTU_DISTRO --ros-distro $CI_ROS_DISTRO 
    - sed -i 's/dh  $@/dh  $@ --parallel/' debian/rules 
    - sed -i 's?v4r\//usr\/lib\/?v4r/usr/lib/:$(CURDIR)/debian/v4r/usr/share/V4R/3rdparty/lib/?' debian/rules
    - cat debian/rules
    - debuild -rfakeroot -us -uc -b -j8
    - mkdir build 
    - mv ../*.deb build 
 
  # This stage is only executed for new tags 
  only: 
    - tags 
 
  # The files which are to be made available in GitLab 
  artifacts: 
    paths: 
    - build/* 
